"""empty message

Revision ID: 1a641d1eef10
Revises: 
Create Date: 2020-04-01 20:07:57.514817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a641d1eef10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value1', sa.String(length=512), nullable=False),
    sa.Column('value2', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('test')
    # ### end Alembic commands ###
