"""empty message

Revision ID: 868bd1b568a8
Revises: a1956292f93c
Create Date: 2020-03-27 21:40:42.800996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868bd1b568a8'
down_revision = 'a1956292f93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value1', sa.String(length=512), nullable=False),
    sa.Column('value2', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
